before_script:
  - gem install bundler -v 1.10.4
  - bundle install

rspec:
  script:
    - -rake spec
    - 'rubocop --config .rubocop.yml --force-exclusion'
  tags:
    - ruby
  only:
    - branches
